// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/collector.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepositoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositoryInfo) Reset() {
	*x = RepositoryInfo{}
	mi := &file_api_proto_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryInfo) ProtoMessage() {}

func (x *RepositoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryInfo.ProtoReflect.Descriptor instead.
func (*RepositoryInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_collector_proto_rawDescGZIP(), []int{0}
}

func (x *RepositoryInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RepositoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StarsCount    int32                  `protobuf:"varint,3,opt,name=starsCount,proto3" json:"starsCount,omitempty"`
	Forks         int32                  `protobuf:"varint,4,opt,name=forks,proto3" json:"forks,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_api_proto_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_api_proto_collector_proto_rawDescGZIP(), []int{1}
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repository) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Repository) GetStarsCount() int32 {
	if x != nil {
		return x.StarsCount
	}
	return 0
}

func (x *Repository) GetForks() int32 {
	if x != nil {
		return x.Forks
	}
	return 0
}

func (x *Repository) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_api_proto_collector_proto protoreflect.FileDescriptor

const file_api_proto_collector_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/collector.proto\x12\tcollector\":\n" +
	"\x0eRepositoryInfo\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x96\x01\n" +
	"\n" +
	"Repository\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"starsCount\x18\x03 \x01(\x05R\n" +
	"starsCount\x12\x14\n" +
	"\x05forks\x18\x04 \x01(\x05R\x05forks\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt2U\n" +
	"\x10CollectorService\x12A\n" +
	"\rgetRepository\x12\x19.collector.RepositoryInfo\x1a\x15.collector.RepositoryB\x11Z\x0fcollector/protob\x06proto3"

var (
	file_api_proto_collector_proto_rawDescOnce sync.Once
	file_api_proto_collector_proto_rawDescData []byte
)

func file_api_proto_collector_proto_rawDescGZIP() []byte {
	file_api_proto_collector_proto_rawDescOnce.Do(func() {
		file_api_proto_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_collector_proto_rawDesc), len(file_api_proto_collector_proto_rawDesc)))
	})
	return file_api_proto_collector_proto_rawDescData
}

var file_api_proto_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_collector_proto_goTypes = []any{
	(*RepositoryInfo)(nil), // 0: collector.RepositoryInfo
	(*Repository)(nil),     // 1: collector.Repository
}
var file_api_proto_collector_proto_depIdxs = []int32{
	0, // 0: collector.CollectorService.getRepository:input_type -> collector.RepositoryInfo
	1, // 1: collector.CollectorService.getRepository:output_type -> collector.Repository
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_collector_proto_init() }
func file_api_proto_collector_proto_init() {
	if File_api_proto_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_collector_proto_rawDesc), len(file_api_proto_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_collector_proto_goTypes,
		DependencyIndexes: file_api_proto_collector_proto_depIdxs,
		MessageInfos:      file_api_proto_collector_proto_msgTypes,
	}.Build()
	File_api_proto_collector_proto = out.File
	file_api_proto_collector_proto_goTypes = nil
	file_api_proto_collector_proto_depIdxs = nil
}
